### PR TITLE
Little optimizations with substantial gains

### PR DESCRIPTION
**Pull request by suvarchal**
- [x] Optimize function [get_no_cyclic](https://github.com/FESOM/pyfesom2/blob/2b06d07ad7698d7dca9130ad0881c83f28365e46/pyfesom2/ut.py#L696). Replace non vectorized python loop with vectorized numpy argwhere function. This gives about 9x(on my machine ~9s to ~1s) performance gain for AO1km mesh. More gain for smaller mesh sizes.
- [x] Optimize function [cut_region](https://github.com/FESOM/pyfesom2/blob/2b06d07ad7698d7dca9130ad0881c83f28365e46/pyfesom2/ut.py#L618). Performance gain about 2X-4+X depending on box size in AO1km mesh and uses less memory. Performance and memory gains are due to using less array comparisons by selecting directly on nodes and using selection bool array for selecting elements.
- [x] An oops bug, [missing parenthesis](https://github.com/FESOM/pyfesom2/blob/2b06d07ad7698d7dca9130ad0881c83f28365e46/pyfesom2/pfplot.py#L173) that crept in from a clean up fdec079.

### CODE REVIEW

**Comment by koldunovn** [comment]
Thanks, Suvi! I will try to have a look ASAP.

**Comment by suvarchal** [comment]
Just  realized, there is probably unnecessary formatting (removing some trailing spaces by my formatter) guess that is fine. Because the changes are small, if your re curious to see, it might be easy using this [example](https://gist.github.com/suvarchal/caff707b6b17c28a6c4ae75528cc6e07#file-ut_optimizations_perf_tests-ipynb). This is for comparing differences to existing so using master/release pyfesom2.


```python
import numpy as np
import pyfesom2
```


```python
mesh = pyfesom2.load_mesh("../../../fesom2/AO1_MESH/") # load AO1 mesh
```

    /home/suvarchal/AWI/fesom2/AO1_MESH/pickle_mesh_py3_fesom2
    The usepickle == True)
    The pickle file for FESOM2 exists.
    The mesh will be loaded from /home/suvarchal/AWI/fesom2/AO1_MESH/pickle_mesh_py3_fesom2


# check perf of opt get_no_cyclic 


```python
from pyfesom2.ut import get_no_cyclic
```


```python
def opt_get_no_cyclic(mesh, elem_no_nan):
    """Compute non cyclic elements of the mesh."""
    d = mesh.x2[elem_no_nan].max(axis=1) - mesh.x2[elem_no_nan].min(axis=1)
    no_cyclic_elem = np.argwhere(d < 100)
    return no_cyclic_elem.ravel()
```


```python
## dont use time it becuse get_no_cyclic in current mster is too slow
```


```python
%%time
non_cyclic_elem = get_no_cyclic(mesh, mesh.elem)
```

    CPU times: user 9.41 s, sys: 925 ms, total: 10.3 s
    Wall time: 10.3 s



```python
%%time
opt_non_cyclic_elem = opt_get_no_cyclic(mesh, mesh.elem)
```

    CPU times: user 1.07 s, sys: 1.06 s, total: 2.13 s
    Wall time: 2.15 s



```python
assert np.all(np.asarray(non_cyclic_elem) == opt_non_cyclic_elem)
```

## check perf of opt cut_region 


```python
from pyfesom2.ut import cut_region
```


```python
def opt_cut_region(mesh, box):
    left, right, down, up = box
    
    selection = (
        (mesh.x2 >= left)
        & (mesh.x2 <= right)
        & (mesh.y2 >= down)
        & (mesh.y2 <= up)
    )

    elem_selection = selection[mesh.elem]    
    
    no_nan_triangles = np.all(elem_selection, axis=1) 
    
    elem_no_nan = mesh.elem[no_nan_triangles]
    
    return elem_no_nan, no_nan_triangles
```


```python
# a box for selection, bigger domains 
bbox = [10,40,0,30] # [-180,180, 0, 90]
```


```python
### timeit can be used here because it is fast
```


```python
%%timeit
tri,ind_tri =cut_region(mesh, bbox)
```

    1.74 s ± 77.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



```python
%%timeit
opt_tri, opt_ind_tri = opt_cut_region(mesh, bbox)
```

    198 ms ± 6.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)



```python
tri,ind_tri =cut_region(mesh, bbox)
opt_tri, opt_ind_tri = opt_cut_region(mesh, bbox)
```


```python
# a quick test both old and opt version give same result
assert np.all(ind_tri == opt_ind_tri)
```


```python
assert np.all(tri.ravel() == opt_tri.ravel())
```


```python

```

here is gist [ut_optimizations_perf_tests-ipynb](https://gist.github.com/suvarchal/caff707b6b17c28a6c4ae75528cc6e07#file-ut_optimizations_perf_tests-ipynb)

**Comment by suvarchal** [comment]
> Thanks, Suvi! I will try to have a look ASAP.

No rush from my  side.

**Review by koldunovn — APPROVED** [review]
Suvi, thanks a lot, it's perfect :) I have updated also the mesh creation with this optimization.

**Review by suvarchal — COMMENTED** [review]
changes seem okay, merging with master.

**Pull request merged**
