### PR TITLE
Feat/ollie ci

### PR DESCRIPTION
**Pull request by pgierz**
First successful run of pyfesom2 test suite on ollie bare-metal :-) 🎉 🥳 

There are a few things I would still like to discuss:

* Currently, I had to setup my own miniconda environment on the test account. We could swap that out for a singularity contaner
* I need to set quite a lot of the env variables in the CI definition, it would be nice if the runner inherited the one from the shell (that doesn't seem to be possible)
* Would it make sense to containerize the runner itself?
* I still need to add the self-hosted runner to the FESOM organization, but I need to be org-owner to do that.

### CODE REVIEW

**Comment by pgierz** [comment]
Also of interest perhaps for @rakowsk

**Comment by pgierz** [comment]
We can do it together at the hackathon next week

**Comment by suvarchal** [comment]
> We can do it together at the hackathon next week

What was this, did i miss something (or lot of things :)) :D

**Comment by pgierz** [comment]
We had the option of running CI directly on the supercomputer, which is nice because mocking all the complexity of HPC on GitHub's Ubuntu is challenging. Possible, but challenging. 

If this is still of interest, I can set the same thing up on Albedo; I don't think Ollie is still worthwhile since we will decommission the machine in a few months. 

It might be nice to CI directly on HPC for the model itself as well

**Pull request closed without merging**
