### PR TITLE
feat: flexible naming convention (Closes #162 (partially))

### LINKED ISSUE #162: More flexible name for loading data into pyfesom2 or adapting esm_tools to pyfesom2 nameing convention
Currently esm_tools move FESOM2 output files into an output folder and rename them from eg.
`ist.fesom.1992.nc` to `ist.fesom.199201.01.nc`. The reason is that FESOM2 normally keeps everything in the work folder in between runs. Thus if a run is less than one year long, FESOM2 just keeps adding timesteps to the output files. Esm_tools on the other hand moves all files into outdata/fesom/. Therefore it would overwrite the existing file. The solution was to give an this additional string.

pyfesom2 does not find these files when operating e.g. inside [fdiag](https://github.com/FESOM/fdiag). At the moment users that produce FESOM2 data with esm_tools that read the data via pyfesom2 handle this case with bash scrips that rename the files. We can do better. Which side should be changed, esm_tools or pyfesom2?

### PR DESCRIPTION
**Pull request by pgierz**
Hi @koldunovn, @JanStreffing, @mandresm

Here is a preliminary workaround for pyfesom2 get_data with esm-tools. It should work for yearly runs. Can be improved, but, better than renaming everything by hand...

### CODE REVIEW

**Comment by pgierz** [comment]
And please ignore the auto-black formatter, my vim did that without asking me...

**Comment by koldunovn** [comment]
Thanks a lot @pgierz ! It finally closes #162 :)

**Comment by koldunovn** [comment]
@JanStreffing after your OK I will merge.

**Comment by JanStreffing** [comment]
Thank you Paul!
I just looked at one of my AWI-CM3 output/fesom folders. I found it strange that this problem had not bugged me in quite a while. I noticed that my fesom2 output there now has names like:

m_snow.fesom.2040.nc
Did something change on the esm_tools side? Or was this always only a problem for runs that are less than 1 year long?

**Review by JanStreffing — APPROVED** [review]

**Comment by koldunovn** [comment]
> Thank you Paul! I just looked at one of my AWI-CM3 output/fesom folders. I found it strange that this problem had not bugged me in quite a while. I noticed that my fesom2 output there now has names like:
> 
> m_snow.fesom.2040.nc Did something change on the esm_tools side? Or was this always only a problem for runs that are less than 1 year long?

I think at some point @mandresm get tide of pyfesom2 users complaints and add fix to some versions of ESMTools :)

**Comment by koldunovn** [comment]
@pgierz Let's wait with conda version, there is no capacity from my side to deal with it now :)

**Comment by pgierz** [comment]
For me also: No time, too many things at once! But, it should not get forgotten. I might have some time tomorrow on the train.

**Comment by pgierz** [comment]
It is already merged, but some final ideas to maybe consider for the future:

@mandresm: I think the relevant output line is [this one:](https://github.com/esm-tools/esm_tools/blob/d5c7ccde137b7309012f83ccf9cc03c8ad113f06/configs/components/fesom/fesom-2.1.yaml#L147)

```yaml
outdata_targets:
        fesom: "*.fesom.*${start_date!smonth}.${start_date!sday}.nc"
```

I think the important part is this `.${start_date!sday}` element. I am unsure who thought of it or why we needed to append the day to the filename; no tool that I know of ever needed this. Or are there circumstances when FESOM is run in a mode with daily output generation?

In any case, I hope my changes for pyfesom2 will allow for more flexible reading with the standard `get_data` routines. We might consider rearranging on the esm-tools side to be more consistent with the other models. I would prefer something like:

```
${expid}_fesom_main_${date_start}-${date_end}.nc
```

I think for `esm-tools` it would rather take the form:
```
${general.expid}_fesom_${fesom.output_stream}_${start_date!syear}${start_date!smonth}${start_date!sday}-${end_date!syear}${end_date!smonth}${end_date!sday}.nc
```

You could then also have as `output_stream` things like: `fesom_cvmix`, `fesom_bgc`, or whatever else might be desired. That closely mirrors ECHAM (@JanStreffing, maybe also OIFS?), and the renaming can be done easily enough on the esm-tools side, and with the switch in the function, it should be possible that the "pure fesom" colleagues do not need to change their workflows.

...and of course, @koldunovn will want all of us to move to zarr, so all this netcdf stuff will puff away into thin air ;-)

**Comment by JanStreffing** [comment]
OIFS output via XIOS is currently configured to be one file per variable and output frequency. The user can define how often the files shall be split. Currently we have it set to yearly. So you might get output like:
```
atm_remapped_1m_10u_1m_2020-2020.nc
atm_remapped_6h_10u_6h_2020-2020.nc
atm_remapped_1m_10u_1m_2021-2021.nc
atm_remapped_6h_10u_6h_2021-2021.nc
```
In general the naming scheme is quite flexible and can be defined in the `file_def.xml`

Sorry for going somewhat off topic, but does the move to zarr really require a new file format? 
See: https://medium.com/pangeo/cloud-performant-netcdf4-hdf5-with-zarr-fsspec-and-intake-3d3a3e7cb935
I took that as we can have the performance of zarr and the backwards compatibility of netcdf. Only some smart chunking choices required.

**Comment by pgierz** [comment]
To the off topic comment about zarr: one of the many things we should have in some sort of semi regular data wrangling hack day to trade ideas (once a month?)  somehow Covid put a big break into those sorts of discussions. 

Thanks for the post link, something to look into.

**Pull request merged**
